In [2]:
#創建陣列
import numpy as np
np1 = np.array([1,2,3,4])	#使用list
np2 = np.array((5,6,7,8))	#使用tuple
print(np1)
print(np2)
print(type(np1), type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:
#設定陣列資料型態
na = np.array([1,2,3,4], dtype=int)
print(na)
na = np.array([1,2,3,4], dtype=float)
print(na)

In [ ]:
#創建陣列
a = np.zeros((5,))
print(a)
b = np.ones((5,))
print(b)
c = np.empty(10)
print(c)
na = np.arange(0, 31, 2)
print(na)
na = np.linspace(1, 15, 3)
print(na)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1.26894556e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 4.01781735e-057 7.61483637e+169 7.79296108e-091
 4.27858606e-033 4.49304643e-315]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 1.  8. 15.]


In [ ]:
#隨機陣列
print('1.產生2x3 0~1之間的隨機浮點數\n',
      np.random.rand(2,3))
print('2.產生2x3常態分佈的隨機浮點數\n',
      np.random.randn(2,3))
print('3.產生0~4(不含5)隨機整數\n',
      np.random.randint(5))
print('4.產生2~4(不含5)5個隨機整數\n',
      np.random.randint(2,5,[5]))
print('5.產生3個 0~1之間的隨機浮點數\n',
      np.random.random(3),'\n',
      np.random.random_sample(3),'\n',
      np.random.sample(3))
print('6.產生0~4(不含5)2x3的隨機整數\n',
      np.random.choice(5,[2,3]))
print('7.產生0~42(不含43)6個不重複的隨機整數\n',
      np.random.choice(43,6,replace=False))

1.產生2x3 0~1之間的隨機浮點數
 [[0.2245752  0.14413795 0.75667269]
 [0.22794922 0.96571221 0.6325971 ]]
2.產生2x3常態分佈的隨機浮點數
 [[ 0.43876202 -0.21549923  0.6216572 ]
 [ 0.65956354  0.45820885 -0.46600932]]
3.產生0~4(不含5)隨機整數
 4
4.產生2~4(不含5)5個隨機整數
 [3 4 2 3 4]
5.產生3個 0~1之間的隨機浮點數
 [0.45929931 0.03099603 0.26345831] 
 [0.14483555 0.37983593 0.05680608] 
 [0.35069166 0.02567525 0.09804703]
6.產生0~4(不含5)2x3的隨機整數
 [[4 4 3]
 [1 3 1]]
7.產生0~42(不含43)6個不重複的隨機整數
 [42  6 30 12 17 10]


In [6]:
#陣列屬性
listdata = [[1,2,3,4,5],
       [6,7,8,9,10],
       [11,12,13,14,15]]
na = np.array(listdata)
print(na)
print('維度', na.ndim)
print('形狀', na.shape)
print('數量', na.size)
print('資料型態', na.dtype)
print('陣列中元素的大小', na.itemsize)
print('陣列的大小', na.nbytes)
ans=[]
for i in listdata:
  x=[]
  for j in i:
    if j%2!=0:
      x.append(j)
    ans.append(x)
print(ans)
  

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
維度 2
形狀 (3, 5)
數量 15
資料型態 int64
陣列中元素的大小 8
陣列的大小 120
[[1, 3, 5], [1, 3, 5], [1, 3, 5], [1, 3, 5], [1, 3, 5], [7, 9], [7, 9], [7, 9], [7, 9], [7, 9], [11, 13, 15], [11, 13, 15], [11, 13, 15], [11, 13, 15], [11, 13, 15]]


In [ ]:
#改變陣列的形狀
adata = np.arange(1,17)
print(adata)
bdata = adata.reshape(4,4)
print(bdata)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#陣列串接
x = [1,2,3]
y = [4,5,6]
print('concatenate', np.concatenate([x,y]))
print('vstack', np.vstack([x,y]))
print('hstack', np.hstack([x,y]))

concatenate [1 2 3 4 5 6]
vstack [[1 2 3]
 [4 5 6]]
hstack [1 2 3 4 5 6]


In [ ]:
#陣列分割
z=np.array([1,2,3,4,5,6,7,8,9])
print('split', np.split(z,[3,5]))

z=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('vsplit', np.vsplit(z,[2]))
print('hsplt', np.hsplit(z,[2]))

split [array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]
vsplit [array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]
hsplt [array([[1, 2],
       [4, 5],
       [7, 8]]), array([[3],
       [6],
       [9]])]


In [ ]:
#一維陣列取值
na = np.arange(0,6)
print(na)           
print(na[0])          
print(na[5])        
print(na[1:5])      
print(na[1:5:2])    
print(na[5:1:-1])   
print(na[:])        
print(na[:3])       
print(na[3:])       

[0 1 2 3 4 5]
0
5
[1 2 3 4]
[1 3]
[5 4 3 2]
[0 1 2 3 4 5]
[0 1 2]
[3 4 5]


In [ ]:
#多維陣列取值
na = np.arange(1, 17).reshape(4, 4)
print(na[2, 3])			#12
print(na[1, 1:3])		#[6,7]
print(na[1:3, 2])		#[7,11]
print(na[1:3, 1:3])		#[[6,7],[7,11]]
print(na[::2, ::2])		#[[1,3],[9,11]]
print(na[:, 2])			#[3,7,11,15]
print(na[1, :])			#[5,6,7,8]
print(na[:, :])			#矩陣全部

12
[6 7]
[ 7 11]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]]
[ 3  7 11 15]
[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#陣列運算
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print('a 陣列內容：\n', a)
print('b 陣列內容：\n', b)
print('a 陣列元素都加值：\n', a + 1)
print('a 陣列元素都平方：\n', a ** 2)
print('a 陣列元素加判斷：\n', a < 5)
print('a 陣列取出第一個row都加1：\n', a[0,:] + 1)
print('a 陣列取出第一個col都加1：\n', a[:,0] + 1)
print('a b 陣列對應元素相加：\n', a + b)
print('a b 陣列對應元素相乘：\n', a * b)
print('a b 陣列點積計算：\n', np.dot(a,b))

a 陣列內容：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b 陣列內容：
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
a 陣列元素都加值：
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
a 陣列元素都平方：
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
a 陣列元素加判斷：
 [[ True  True  True]
 [ True False False]
 [False False False]]
a 陣列取出第一個row都加1：
 [2 3 4]
a 陣列取出第一個col都加1：
 [2 5 8]
a b 陣列對應元素相加：
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
a b 陣列對應元素相乘：
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
a b 陣列點積計算：
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [ ]:
#陣列的計算與統計
a = np.arange(1,10).reshape(3,3)
print('陣列的內容：\n', a)
print('1.最小值與最大值：\n',
      np.min(a), np.max(a))
print('2.每一直行最小值與最大值：\n',
      np.min(a, axis=0), np.max(a, axis=0))
print('3.每一橫列最小值與最大值：\n',
      np.min(a, axis=1), np.max(a, axis=1))
print('4.加總、乘積及平均值：\n',
      np.sum(a), np.prod(a), np.mean(a))
print('5.每一直行加總、乘積與平均值：\n',
      np.sum(a, axis=0), np.prod(a, axis=0), np.mean(a, axis=0))
print('6.每一橫列加總、乘積與平均值：\n',
      np.sum(a, axis=1), np.prod(a, axis=1), np.mean(a, axis=1))


In [ ]:
#陣列的計算與統計
a = np.random.randint(100,size=50)
print('陣列的內容：', a)
print('1.標準差：', np.std(a))
print('2.變異數：', np.var(a))
print('3.中位數：', np.median(a))
print('4.百分比值：', np.percentile(a, 80))
print('5.最大最小差值：', np.ptp(a))

In [ ]:
#一維陣列排序
a = np.random.choice(50, size=10, replace=False)
print('排序前的陣列：', a)
print('排序後的陣列：', np.sort(a))
print('排序後的索引：', np.argsort(a))
#用索引到陣列取值
for i in np.argsort(a):
    print(a[i], end=',')

排序前的陣列： [21 36  1 26 16  5 13 31 46 48]
排序後的陣列： [ 1  5 13 16 21 26 31 36 46 48]
排序後的索引： [2 5 6 4 0 3 7 1 8 9]
1,5,13,16,21,26,31,36,46,48,

In [ ]:
#多維陣列排序
a = np.random.randint(0,10,(3,5))
print('原陣列內容：')
print(a)
print('將每一直行進行排序：')
print(np.sort(a, axis=0))
print('將每一橫列進行排序：')
print(np.sort(a, axis=1))

原陣列內容：
[[6 3 2 4 3]
 [7 7 3 5 8]
 [6 9 6 5 6]]
將每一直行進行排序：
[[6 3 2 4 3]
 [6 7 3 5 6]
 [7 9 6 5 8]]
將每一橫列進行排序：
[[2 3 3 4 6]
 [3 5 7 7 8]
 [5 6 6 6 9]]
